from easydict import EasyDict as edict
import math

__C = edict()

cfg = __C

# the camera
__C.CAMERA = edict()
__C.CAMERA.RESOLUTION_X = 900
__C.CAMERA.RESOLUTION_Y = 1200
__C.CAMERA.PERCENTAGE = 100 # 100

__C.CAMERA.SAMPLE = 256

# the camera 1
__C.CAMERA1 = edict()
__C.CAMERA1.LOCATION_X = 0
__C.CAMERA1.LOCATION_Y = 0
__C.CAMERA1.LOCATION_Z = 13

__C.CAMERA1.ROTATION_X = math.pi * 0 / 180
__C.CAMERA1.ROTATION_Y = 0
__C.CAMERA1.ROTATION_Z = math.pi * 0 / 180


# the camera 2
__C.CAMERA2 = edict()
__C.CAMERA2.LOCATION_X = 0
__C.CAMERA2.LOCATION_Y = -7
__C.CAMERA2.LOCATION_Z = 7

__C.CAMERA2.ROTATION_X = math.pi * 35 / 180
__C.CAMERA2.ROTATION_Y = 0
__C.CAMERA2.ROTATION_Z = 0

# the camera 3
__C.CAMERA3 = edict()
__C.CAMERA3.LOCATION_X = -5.5
__C.CAMERA3.LOCATION_Y = 0
__C.CAMERA3.LOCATION_Z = 4.5

__C.CAMERA3.ROTATION_X = math.pi * 40 / 180
__C.CAMERA3.ROTATION_Y = 0
__C.CAMERA3.ROTATION_Z = math.pi * -90 / 180

# the camera 4
__C.CAMERA4 = edict()
__C.CAMERA4.LOCATION_X = -4
__C.CAMERA4.LOCATION_Y = -6
__C.CAMERA4.LOCATION_Z = 4

__C.CAMERA4.ROTATION_X = math.pi * 45 / 180
__C.CAMERA4.ROTATION_Y = 0
__C.CAMERA4.ROTATION_Z = math.pi * -30 / 180

# the camera 5
__C.CAMERA5 = edict()
__C.CAMERA5.LOCATION_X = 4
__C.CAMERA5.LOCATION_Y = 6
__C.CAMERA5.LOCATION_Z = 4

__C.CAMERA5.ROTATION_X = math.pi * 45 / 180
__C.CAMERA5.ROTATION_Y = 0
__C.CAMERA5.ROTATION_Z = math.pi * 150 / 180


# the image plane
__C.PLANE = edict()
__C.PLANE.LOCATION_X = 0
__C.PLANE.LOCATION_Y = 0
__C.PLANE.LOCATION_Z = 0

__C.PLANE.ROTATION_X = 0
__C.PLANE.ROTATION_Y = 0
__C.PLANE.ROTATION_Z = 0


__C.PLANE.DIMENSION_X = 9
__C.PLANE.DIMENSION_Y = 12
__C.PLANE.DIMENSION_Z = 1


# the occluder
__C.OBJECT = edict()
__C.OBJECT.LOCATION_X = 0
__C.OBJECT.LOCATION_Y = 0
__C.OBJECT.LOCATION_Z = 18

__C.OBJECT.ROTATION_X = 0
__C.OBJECT.ROTATION_Y = 0
__C.OBJECT.ROTATION_Z = 0

__C.OBJECT.SCALE_X = 1
__C.OBJECT.SCALE_Y = 3
__C.OBJECT.SCALE_Z = 0.2

__C.OBJECT.LOCATION_MIN = -1
__C.OBJECT.LOCATION_MAX = 1
__C.OBJECT.LOCATION_Z_MIN = 14
__C.OBJECT.LOCATION_Z_MAX = 18


__C.OBJECT.ROTATION_MIN = math.pi * 0 / 180
__C.OBJECT.ROTATION_MAX = math.pi * 90 / 180


# the hdri
__C.HDRI = edict()
__C.HDRI.STRENGTH_MIN = 0.1
__C.HDRI.STRENGTH_MAX = 0.3


# the light source
__C.LIGHT = edict()
__C.LIGHT.TYPE = 'SPOT'
__C.LIGHT.ANGLE = math.pi * 45 / 180
__C.LIGHT.SHADOW_SOFT_MIN = 0.3 # 0.3 ~ 0.8
__C.LIGHT.SHADOW_SOFT_MAX = 0.8 # 0.3 ~ 0.8

__C.LIGHT.STRENGTH_MIN = 3000 # 3000 ~ 10000
__C.LIGHT.STRENGTH_MAX = 10000 # 3000 ~ 10000


__C.LIGHT.LOCATION_X = 0
__C.LIGHT.LOCATION_Y = 0
__C.LIGHT.LOCATION_Z = 22

__C.LIGHT.ROTATION_X = 0
__C.LIGHT.ROTATION_Y = 0 
__C.LIGHT.ROTATION_Z = 0
